### ISSUE TITLE
PHP8.1 urlencode(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by sreichel** [Shardj/zf1-future#308]
```
#0 [internal function]: mageCoreErrorHandler(8192, 'urlencode(): Pa...', '/var/www/html/v...', 343)
#1 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Data.php(343): urlencode(NULL)
#2 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale.php(1466): Zend_Locale_Data::getList('de_DE', 'language', NULL)
#3 /var/www/html/app/code/core/Mage/Core/Model/Locale.php(237): Zend_Locale::getTranslationList('language', 'de_DE')
```

```php
public static function getTranslationList($path = null, $locale = null, $value = null)
```

```php
public static function getList($locale, $path, $value = false)
```

**Comment by sreichel** [comment]
Closed. Line changed in another patch.
