### ISSUE TITLE
Remove manual require_once calls

### ISSUE THREAD

**Issue by staabm** [Shardj/zf1-future#348]
the [zf1-future fork is using composer for autoloading](https://github.com/Shardj/zf1-future/blob/7fa9c5f50f0ce8ceecafb13e107eebe4c3d04051/composer.json#L19-L23).

still it contains a lot of `require_once` calls in its codebase, e.g. 

https://github.com/Shardj/zf1-future/blob/7fa9c5f50f0ce8ceecafb13e107eebe4c3d04051/library/Zend/Controller/Front.php#L23-L30

these require once calls are harmful for static analysis.
for best [performance and most accurate results PHPStan](https://phpstan.org/blog/zero-config-analysis-with-static-reflection) suggests to use regular composer autoloading instead of manual require/include calls.

since the composer autoloader is configured, I would like to propose dropping require calls where possible for a more relieable static analysis experience.

whats your opinion on this? PR welcome?

----

our concrete problem at hand: we run into fatal errors while running phpstan because of this require_once calls:

```
Internal error: Internal error: Class "Zend_Controller_Plugin_Abstract" not found in file C:\dvl\daiber\application\B2B\controllers\ArticleController.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
     #0 C:\dvl\daiber\vendor\shardj\zf1-future\library\Zend\Controller\Front.php(30): require_once()
     #1 C:\dvl\daiber\vendor\shardj\zf1-future\library\Zend\Controller\Action.php(35): require_once('...')
     #2 C:\dvl\daiber\library\clxProductNet\library\Clx\Controller\Action.php(8): require_once('...')
     #3 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php(582): include('...')
     #4 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
     #5 C:\dvl\daiber\application\B2B\controllers\ArticleController.php(16): Composer\Autoload\ClassLoader->loadClass()
     #6 C:\dvl\daiber\vendor\plugins\rocket\lib\Rocket.php(411): require_once('...')
     #7 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/AutoloadFunctionsSourceLocator.php(41): Rocket::autoload()
     #8 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(26): PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadFunctionsSourceLocator->locateIdentifier()
     #9 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(33): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
     #10 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/DefaultReflector.php(32): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier()
     #11 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingReflector.php(45): PHPStan\BetterReflection\Reflector\DefaultReflector->reflectClass()
     #12 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/BetterReflectionProvider.php(163): PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector->reflectClass()
     #13 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(43): PHPStan\Reflection\BetterReflection\BetterReflectionProvider->getClass()
     #14 C:\dvl\daiber\vendor\phpstan\phpstan-deprecation-rules\src\Rules\Deprecations\ImplementationOfDeprecatedInterfaceRule.php(45): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->getClass()
     #15 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): PHPStan\Rules\Deprecations\ImplementationOfDeprecatedInterfaceRule->processNode()
     #16 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(417): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
     #29 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()
     #30 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_532094bc1\Symfony\Component\Console\Command\Command->run()
     #31 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_532094bc1\Symfony\Component\Console\Application->doRunCommand()
     #32 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_532094bc1\Symfony\Component\Console\Application->doRun()
     #33 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(122): _PHPStan_532094bc1\Symfony\Component\Console\Application->run()
     #34 phar://C:/dvl/daiber/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(123): _PHPStan_532094bc1\{closure}()
     #35 C:\dvl\daiber\vendor\phpstan\phpstan\phpstan(8): require('...')
     #36 C:\dvl\daiber\vendor\bin\phpstan(120): include('...')
     #37 {main}
     Child process error (exit code 1):
     ```

as soon as we drop the require calls, these errors do no longer appear

**Comment by glensc** [comment]
I think zf-future claims to be compatible with origina zendframework, and using that loader, not composer.
i think this has been discussed already before in the issues.

if you want composer only, use zf1s:
- https://github.com/zf1s/zf1

**Comment by staabm** [comment]
my point was not about dropping the zend loaders or loader classes but only dropping the manual `require` calls

**Comment by glensc** [comment]
and my reply point was that original zendframework expected the require_once calls to be in the code.

**Comment by tsmgeek** [comment]
https://github.com/Shardj/zf1-future/issues/37

**Comment by wex** [comment]
This would break "drop-in" compatibility quite badly - for example: by requiring Zend_Config & Zend_Db you can easily factory Zend_Db_Adapter based on Zend_Config without any autoloading. I can only guess how many legacy applications there are relaying on this functionality around the world.

**Comment by develart-projects** [comment]
Imo - no way. I have HUGE ZF1 codebase and last thing we need to rework in company is reworking the class names.
@staabm any possibility to suppress STAN by annotations? I'm not really using STAN, so can't say.

**Comment by rruchte** [comment]
Yeah, the whole point of this project is to not break BC. It's a no for me.

**Comment by staabm** [comment]
Thanks for your input

**Comment by sreichel** [comment]
Used [that](https://github.com/OpenMage/magento-lts/blob/v19.4.0/lib/Zend/replace_recursive.php) script to create a patch.

https://gist.github.com/sreichel/635d0c9858bec04a6dd46fc1f85bc3e3

Maybe add it or link it in README.
